# ebean configuration
ebean:
  dumpMetricsOnShutdown: true
  dumpMetricsOptions: loc,sql,hash
  ddl:
    generate: false
    run: false
  debug:
    sql: true
    lazyload: true
  logging: all

# database configuration
datasource:
  db:
    username: conserjeria
    password: 79z#5RX&qq5z
    platform: mariadb # h2, postgres, mysql, oracle, sqlserver
    ddlMode: none # none | dropCreate | migrations
    dbName: conserjeria
    url: jdbc:mariadb://localhost:3306/conserjeria
