version: '3.8'

services:
  conserjeria:
    build: .
    ports:
      - "7070:7070"
    volumes:
      - ./Application.yaml:/app/Application.yaml
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx256m
    command: ["java", "-jar", "conserjeria.jar", "--spring.config.location=file:./Application.yaml"]

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
